### ISSUE TITLE
ScrollbarsProvider doesn't work...

### ISSUE THREAD

**Issue by eHxBes** [iominh/ng-scrollbars#1]
Setting the configuration in a scope variable works... but it doesn't when using this :

```
        ScrollBarsProvider.defaults = {
            autoHideScrollbar: true,
            theme: 'dark',
            scrollButtons: {
                enable: true //enable scrolling buttons by default
            },
            axis: 'yx' //enable 2 axis scrollbars by default
        };
```

**Comment by iominh** [comment]
Hey earth4x! I'll take a look tonight. I didn't know anyone even used this library lol.

**Comment by iominh** [comment]
I just pushed a new version where that should work (just update to 0.0.3). Any system-wide defaults you provide will be applied to all scrollbars but if you set a scope configuration then it'll override the provider defaults.

If this works for you then please reply back and I'll close this ticket. Also, feel free to open any other issues/suggestions and if you could star the project that'll really help me too! Thanks :)
