### ISSUE TITLE
collision between 'ng-scrollbars' directive and angular material's 'md-sidenav' directive 

### ISSUE THREAD

**Issue by idanpt** [iominh/ng-scrollbars#10]
Hi, when i try to use ng-scrollbars on md-sidenav, i get this error: (other than that, thanks for this great tool!!)
Error: 
[$compile:multidir] Multiple directives [mdSidenav, ngScrollbars] asking for new/isolated scope on: <md-sidenav ng-scrollbars="" layout="column" class="md-sidenav-left md-whiteframe-z5 md-closed" md-component-id="left" md-is-locked-open="$mdMedia('gt-md')" tabindex="-1">
http://errors.angularjs.org/1.3.6/$compile/multidir?p0=mdSidenav&p1=ngScrollbars&p2=new%2Fisolated<ng-include src="'view/partials/menu.html'" layout="vertical" ng-controller="MenuController" class="ng-scope">cope&p3=%3Cmd-sidenav%20ng-scrollbars%3D%22%22%20layout%3D%column%22%20class%3D%22md-sidenav-left%20md-whiteframe-z5%20md-closed%22%20md-component-id%3D%22left%22%20md-is-locked-open%3D%22%24mdMedia('gt-md')%22%20tabindex%3D%22-1%22%3E
    at REGEX_STRING_REGEXP (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.js:63:12)
    at assertNoDuplicate (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.js:7974:15)
    at applyDirectivesToNode (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.js:7304:15)
    at compileNodes (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.js:6984:15)
    at compile (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.js:6891:15)
    at $compile.link (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.js:23739:9)
    at invokeLinkFn (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.js:8194:9)
    at nodeLinkFn (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.js:7706:11)
    at compositeLinkFn (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.js:7062:13)
    at publicLinkFn (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.js:6941:30)

**Comment by iominh** [comment]
Hi idanpt,

I put together a very rough demo of how to resolve this issue. See http://iominh.github.io/ng-scrollbars/10.html and view the source.

To avoid the conflict, you can put the ng-scrollbars directive in an outside container with a specified width. For example:

``` html
<div class="ng-scrollbar-container" ng-scrollbars style="width: 330px;">
        <md-sidenav class="md-sidenav-left md-whiteframe-z2" md-component-id="left" md-is-locked-open="$mdMedia('gt-md')">

            <md-toolbar class="md-theme-indigo">
                <h1 class="md-toolbar-tools">Sidenav Left</h1>
            </md-toolbar>
            <md-content layout-padding="" ng-controller="LeftCtrl">
                <md-button ng-click="close()" class="md-primary" hide-gt-md="">
                    Close Sidenav Left
                </md-button>
                <p hide-md="" show-gt-md="">
                    This sidenav is locked open on your device. To go back to the default behavior,
                    narrow your display.
                </p>
            </md-content>

        </md-sidenav>
    </div>    
```

Long term, I'll like to make this better but for now hopefully that fixes it for you. If it helps please star the repo, thanks!

**Comment by idanpt** [comment]
actually i didn't have to specify the width, but the height:
<div class="container" ng-scrollbars style="height: 99vh;"> 

thanks! starred!

**Comment by iominh** [comment]
Awesome, I'm glad it works, thanks for the star and let me know if you have any other issues

**Comment by llakhani** [comment]
I have tried to specify ng-scrollbars above the sidenav, but still I'm facing same issue, Multidirective 
Multiple directives [ngController, mdSidenav (module: material.components.sidenav)] asking for new/isolated on: {5}
I'm using angular material v1.1.7
Can any one help me out?
