### ISSUE TITLE
Mac machine Safari Browser

### ISSUE THREAD

**Issue by sam83045** [iominh/ng-scrollbars#12]
This bug is only found on Mac Safari Browser can be seen on demo pages also.
http://iominh.github.io/ng-scrollbars/

Issue is when we scroll upto end the scrolling stops just before end and after 1sec remaining scrolling completed. Same thing happens when we scroll up.

On demo page this is nearly neglible near about 3px. But in my case user can easily find it.

**Comment by sam83045** [comment]
Bug is inherited from  Malihu's jQuery Custom Scrollbar by Manos Malihutsakis. Can't be fixed in this repository. Hence closing the bug.

**Comment by iominh** [comment]
Hi @sam83045, thanks pointing out the issue! I imagine you could probably play with the scrollInertia setting by raising or lowering it (see http://manos.malihu.gr/jquery-custom-content-scroller/). I personally haven't observed this issue in Safari but I imagine I need to add a lot more content in the scrollbar container.

Also if you ever fix it or have a workaround I imagine the Malihu project could benefit from it (https://github.com/malihu/malihu-custom-scrollbar-plugin/issues) and certainly ng-scrollbars as well.

Thanks again!
