### ISSUE TITLE
Scrolling in ngScrollbars div affects adjacent div scrolling

### ISSUE THREAD

**Issue by im1dermike** [iominh/ng-scrollbars#13]
I have a navigation menu on the left side of my page to which I've added `ngScrollbars`.  I've configured it and it works great.  The only problem I'm having is with the page content div which is to the right of the left menu "pane".  I have not implemented `ngScrollbars` to this div; it has the default browser scrollbar when needed (`overflow: auto;`).  I've found that when both the left side and page content are scrollable, when I scroll to the bottom of the `ngScrollbars` div and continue to scroll down, it scrolls down in the adjacent page content div.  Likewise, when I scroll to the top of the `ngScrollbars` div and continue to scroll up, it scrolls up in the adjacent page content div.

This is pretty bizarre behavior that I can't imagine is expected.  Any ideas?  I'm experiencing this in all browsers.  I'm hoping it's just a simple config change...

ps. Thanks for porting the `mCustomScrollbar` jQuery plugin into Angular!

**Comment by im1dermike** [comment]
It turns out there is actually a config setting for this :stuck_out_tongue_winking_eye::

```
mouseWheel: { preventDefault: true }
```

**Comment by iominh** [comment]
Thanks! I'm glad you figured it out and I appreciate the detailed issue
