### ISSUE TITLE
how to implement infinite scrolling lazy load usnig this. 

### ISSUE THREAD

**Issue by lovetrivedi** [iominh/ng-scrollbars#17]
I have too many product and want to use infinite scrolling or lazy load techniques. but how can I get the scroll position. 
Is there any call back to fire a function when user scrolls to the end of the container.

Thanks

**Comment by iominh** [comment]
Hi Ivtrvd,

I'll try to get back to you later with a tested/better answer but off the top of my head, everything that's available in Malihu's scrollbars library is accessible in this directive.

So, you could probably do something like the following:

``` javascript
$scope.config = {
    autoHideScrollbar: false,
    theme: 'light',
    advanced:{
        updateOnContentResize: true
    },
        setHeight: 200,
        scrollInertia: 0
    },
   callbacks: {
    onScroll:function(el){
            console.log(el.mcs.top);
        }
  }
}
```

See the following link: http://manos.malihu.gr/jquery-custom-content-scroller/#callbacks-section

**Comment by lovetrivedi** [comment]
Thanks for your support but I want this on particular view. If I add this in config than this will run on each component of the application.
please correct me if I am wrong.

**Comment by iominh** [comment]
You should be able to set the configuration for individual scrollbars (see the primary demo http://iominh.github.io/ng-scrollbars/). So for the above example, you could change it to $scope.config1 and do the following

``` html
<div ng-scrollbars ng-scrollbars-config="config1">
```

You could also do other individual scrollbar configurations (config2, config3, etc).

Anyway, that's what I remember, I'll need to test it a bit to verify anything I'm saying is correct :)

**Comment by lovetrivedi** [comment]
Its working perfectly 
Thanks
