### ISSUE TITLE
Standalone scrollbar

### ISSUE THREAD

**Issue by jbrukh** [iominh/ng-scrollbars#18]
Is it possible to configure a scrollbar as a standalone object that controls the scrolling of a different element?

**Comment by iominh** [comment]
Anything is possible :). You could add a ["callbacks"](http://manos.malihu.gr/jquery-custom-content-scroller/#callbacks-section) option to an ng-scrollbar config and as it scrolls you could use Angular's emit and broadcast to send events to other elements. When I get some free time I'll see if I can come up with a demo, maybe with two synchronized scroll bars.

Could you describe your use case a bit more? Why would you want to do this?

**Comment by jbrukh** [comment]
I have a design spec which tells me that I need to place a scroll bar away
from the div that it controls, not onto it. :D

So I looked into the callbacks functionality of mCustomScrollbar, but the
problem is that the callbacks (like whileScrolling) don't provide the pixel
or percentage offset of the bar.

According to the mCustomScrollbar documentation, you can get these values
from "this.mcs.topPct" and "this.mcs.draggerTop" but not sure how to get at
these from your directive... any ideas?

**Comment by iominh** [comment]
Ah gotcha. Hmm, those fields should be available in the callback. If not it might be because of the context (this), which may involve updating the ng-scrollbars directive source (feel free to modify, it's just a wrapper really). Or it could be that ng scrollbars is on an older version of Malihu that doesn't have those fields?

I'm a bit tied up today but will see if I can take a closer look over this weekend

**Comment by jbrukh** [comment]
Thank you, much appreciated.

**Comment by iominh** [comment]
Hopefully this demo helps: http://iominh.github.io/ng-scrollbars/18_update_scrollbars.html.
Unfortunately I had to update the ng-scrollbars library, so you'll have to pull in the latest version (0.0.6).
Please let me know if you have any issues or questions, good luck!

**Comment by jbrukh** [comment]
This is great. Thank you very much for the update.
