### ISSUE TITLE
Strict DI

### ISSUE THREAD

**Issue by norkunas** [iominh/ng-scrollbars#2]
Directive doesn't work when strict mode of dependency injection is set.

**Comment by iominh** [comment]
Hey Norkunas, thanks for the ticket! I pushed version 0.0.4, which should fix this (I tested it in the demo app with ng-strict-di at http://minhongrails.github.io/ng-scrollbars/ and also with gulp-ng-annotate as well). Please let me know if it works for you and I'll close this ticket. Also if you could star this repo I'll really appreciate that too!

**Comment by norkunas** [comment]
Can't test it right now but looks good :)
