### ISSUE TITLE
How can you claim that this is a port? You're just wrapping the jQuery plugin

### ISSUE THREAD

**Issue by pwarelis** [iominh/ng-scrollbars#20]
Please update docs to reflect this. You didn't port anything, claiming this is dishonest.

**Comment by iominh** [comment]
Thank you for the feedback. 

The project began with greater ambitions to actually port Malihu's library to Angular but I didn't have enough free time and didn't want to put too much effort into creating an Angular1 version with Angular2 on the horizon. So, there's a mixture of language between "port" and "wrapper". 

I believe "wrapper" better defines the current state so I went ahead and updated the description and package.json for you (see https://github.com/iominh/ng-scrollbars/commit/e88764c760f4c910ac61629654d92458eda8feab)
