### ISSUE TITLE
Error: [$compile:nonassign] Expression 'undefined' used with directive 'ngScrollbars' is non-assignable!

### ISSUE THREAD

**Issue by gelevanog** [iominh/ng-scrollbars#21]
I have caught this error. 
Angular version 1.4.9

**Comment by iominh** [comment]
Hi gelevanog,

I haven't been updating this library recently and haven't tested it with the newer angular versions. I'll take a look later this week or weekend when I get a chance.

Thanks for the issue!

Minh

**Comment by igor-pomogai** [comment]
Hi iominh,

I've faced this issue too. Probably it's the latest changes causing the error, because when I commented out this lines from your directive the error disappeared:

``` javascript
    // scope.ngScrollbarsUpdate = function () {
    //   elem.mCustomScrollbar.apply(elem, arguments);
    // };
    // scope.element = elem;
```

And by the way thanks for this lib.

Igor

**Comment by iominh** [comment]
Thanks Igor, I really appreciate that! I'll give that a shot and will see if I can figure out a better way to do testing for multiple Angular versions

**Comment by vinicius33** [comment]
+1 Also I've this issue.

**Comment by iominh** [comment]
Where did you all come from? lol I didn't think anyone used this library but I'll try to fix this asap

**Comment by vinicius33** [comment]
:smiling_imp:

**Comment by ghost** [comment]
+1, hit me too, angular 1.3.20.
I need to use the 'update' method of the underlying plugin to handle cases where the automatic sizing does not work, so your latest changes are much needed to get it done in the 'angular' way.

**Comment by iominh** [comment]
Thanks all! I believe I've fixed the issue, so if you update to 0.0.7 it should hopefully work again. If you're using bower, just set  `"ng-scrollbars": "#0.0.7"` and `bower install`, which should hopefully pull down the working version. Sorry about that, I rushed 0.0.6 too quickly.

The issue, it seems, is that I didn't make ng-scrollbars-update optional, so Angular threw the undefined error. I guess I might've had something cached during my 0.0.6 testing. Here's the [actual line](https://github.com/iominh/ng-scrollbars/blob/0.0.7/src/scrollbars.js#L30) if anyone's curious: 

```
 scope: {
        ngScrollbarsConfig: '&',
        ngScrollbarsUpdate: '=?',
        element: '=?'
      },
```

I needed to add the ? to make those fields optional...

I tested 0.0.7 with Angular 1.3.20, 1.40, and 1.49 and it worked okay for me (I double-checked my browser source to verify the versions). If anyone wants to play around with different Angular versions, you can just checkout the gh-pages branch and change the bower.json Angular versions. The current live demo is running Angular 1.4.9 (http://iominh.github.io/ng-scrollbars/).

**If others can confirm it works for them then I'll close this ticket**

**Comment by ghost** [comment]
That was quick, thanks.
I guess the minified version is not updated yet. I had to override by bower.json to use the js from the src folder and it worked just fine.

**Comment by iominh** [comment]
My bad, that should be fixed now for 0.0.7 (unfortunately may have to delete your bower_components/ng-scrollbars and reinstall), I moved the tag up to the correct commit (https://raw.githubusercontent.com/iominh/ng-scrollbars/0.0.7/dist/scrollbars.min.js)

**Comment by ghost** [comment]
Had to clean my bower cache too, following steps worked for me

```
bower uninstall ng-scrollbars
bower cache clean ng-scrollbars
bower install
```

All fine now, thanks again.

**Comment by iominh** [comment]
Thanks @gopalraichur! I appreciate the Github star too!

I hope this issue was resolved for everyone. I'm going to close this ticket now but if anyone runs into any issues I can re-open it
