### ISSUE TITLE
Configuration not working

### ISSUE THREAD

**Issue by silverrajat88** [iominh/ng-scrollbars#26]
configuration is not working. I saw a closed issue, which addressed the same problem but I have done everything by the book. Are more people facing this problem?

Please help.

**Comment by silverrajat88** [comment]
HTML:
`<div class="chat-box" ng-scrollbars ng-scrollbars-config="config" ng-mouseenter="mouseEnterChat()" ng-mouseleave="mouseLeaveChat()">`

CONTROLLER JS

```
  $scope.config = {
      callbacks:{
        onTotalScroll:function () {
          console.log("Scrolled to end of content.");
        }
      }
    };
```

this is the code that I wrote. It seems the directive is not able to process the passed config. Any help will be appreciated.

**Comment by silverrajat88** [comment]
Removing this issue, as I my $scope.config was getting initialized after the link function of the ng-scrollbars executed, and therefore the problem.
It would be great if the owner IOMINH can accommodate dynamic changes to the config object.

**Comment by iominh** [comment]
Hi @silverrajat88! Thanks for submitting the issue!  @adalekin submitted [PR25](https://github.com/iominh/ng-scrollbars/pull/25), which may solve your problem. 

I'll be rolling out release 0.0.9 in the near future but in the meantime the master branch code has these changes so you can try it out to see if it helps

**Comment by silverrajat88** [comment]
@iominh Thanks! :)
