### ISSUE TITLE
Package doesn't work with bower new version

### ISSUE THREAD

**Issue by bgambier** [iominh/ng-scrollbars#3]
Hello, and thanks for your plugin !

I noticed that your bower.json file seems to be wrong: the js file linked for "main" is "scrollbar.js", but the right link should be "dist/scrollbars.min.js". So it doesn't work with bower for me without modifying the file (I tried with the last version "1.3.12").

**Comment by iominh** [comment]
Hey bgamblier, thanks a bunch for the star, issue and fix! I went ahead and made that change to 0.0.4, so could you please verify that it works again? If not, I'll re-open this ticket and try again.

I tested it on the test app at http://minhongrails.github.io/ng-scrollbars/, where I wiped the bower_components and ran 'bower install ng-scrollbars --save' and it seems to work.
