### ISSUE TITLE
why my $scope.updateScrollbar('scrollTo', 'bottom') doesn't work?

### ISSUE THREAD

**Issue by ruanhaojian** [iominh/ng-scrollbars#33]
I use the example   'ng-scrollbars ng-scrollbars-update=updateScrollbar'  and the controller is `$timeout(function() {
            $scope.updateScrollbar('scrollTo', 'bottom');
            alert(1)
        });` 
but it show an error is     $scope.updateScrollbar  is not a function.

---

i debugger and find the scope can't sync between the directive and the controller.

**Comment by iominh** [comment]
Hi @ruanhaojian I apologize for my slow response (my full-time job has been really busy). How did you solve this issue? (this can help future users)

**Comment by ruanhaojian** [comment]
I'm not sure.  Maybe it's not your problem.
I use modal bootstrap `var modalInstance = $modal.open({
                        templateUrl: 'userOpinionReplyModal.html',
                        controller: 'UserOpinionReplyModalCtrl',
                        size: "",
                        keyboard : false,
                        resolve: {
                            model: function () {
                                return model;
                            }
                        }
                    });`

Then my controller use update and it show this error.
so I use another controller/directive  in the element to update and then it work.
`
angular.module('app').directive('autoScrollEnd', ['$timeout', function ($timeout) {return {
        restrict: 'AC',
        link: function (scope, el, attrs) {
            $timeout(function() {
                scope.$apply(function () {
                    scope.updateScrollbar && scope.updateScrollbar('scrollTo', 'bottom');
                });

```
        },1000);

    }
};
```

}]);
`

`<div class="modal-body"  ng-scrollbars ng-scrollbars-update="updateScrollbar" auto-scroll-end  style="height: 400px;overflow: auto;">`

**Comment by iominh** [comment]
Ah interesting, thanks for the information! I'm still not too happy with how $timeout needs to be used so hopefully can fix that someday.

**Comment by ikhattab** [comment]
what works for me is to attach callback function to object something like:

``` html
<div ng-scrollbars ng-scrollbars-update="callbacks.updateScrollbar">......</div>
```

``` js
$scope.callbacks = {};
```

``` js
$scope.callbacks.updateScrollbar("scrollTo", "left");
```

**Comment by iominh** [comment]
Thanks @ikhattab!! Glad to hear you found an alternative solution and thanks for sharing!

**Comment by sanket-webmavens** [comment]
$timeout(function() {
    $('#filter_wrapper').mCustomScrollbar("destroy");
});	

This works for me !!

**Comment by ForkInSpace** [comment]
None of the above worked for me. Maybe we could reopen this issue? @iominh
