### ISSUE TITLE
Issues with <md-sidenav>

### ISSUE THREAD

**Issue by vaishnavmhetre** [iominh/ng-scrollbars#39]
I'm using **mailhu custom scrollbar plugin** together with **ngScrollbar.**

It works fine with `<md-content>` but I'm facing issues with `<md-sidenav>`

After execution of this code

```
<md-sidenav md-swipe-left="sidenav_toggle()"
            class="md-sidenav-left md-whiteframe-z2"
            md-is-locked-open="$mdMedia('gt-sm')"
            md-component-id="leftNav"
            md-scroll-y
            ng-scrollbars
            ng-scrollbars-config="vertScrollConfig">

      ...
</md-sidenav>
```

with vertScrollConfig as -

```
$scope.vertScrollConfig = {
                    autoHideScrollbar: false,
                    theme: 'minimal-dark',
                    advanced:{
                        updateOnContentResize: true
                    },
                    axis: 'y',
                    scrollInertia: 400,
                };
```

I receive following $compile:multidir error -

![multidir scrollbar sidenav issue](https://cloud.githubusercontent.com/assets/14543290/17504372/00da4074-5e16-11e6-83bd-cafe47bd77c5.png)

Found some stuff at [Angular Site](http://errors.angularjs.org/1.5.3/$compile/multidir?p0=mdSidenav&p1=%20%28module%3A%20material.components.sidenav%29&p2=ngScrollbars&p3=%20%28module%3A%20ngScrollbars%29&p4=new%2Fisolated%20scope&p5=%3Cmd-sidenav%20md-swipe-left%3D%22sidenav_toggle%28%29%22%20class%3D%22md-sidenav-left%20md-whiteframe-z2%20_md-closed%22%20md-is-locked-open%3D%22%24mdMedia%28%27gt-sm%27%29%22%20md-component-id%3D%22leftNav%22%20ng-scrollbars%3D%22%22%20ng-scrollbars-config%3D%22vertScrollConfig%22%20tabindex%3D%22-1%22%3E) but I didn't understand what to do actually and which is the directive emerging the issue.

Please do respond as detailed as possible as I'm a beginner at this angular stuff.

**Comment by vaishnavmhetre** [comment]
Found a temporary fix..!

```
<script>
        $('md-sidenav').mCustomScrollbar({
              axis: "y",
              autoExpandScrollbar: false,
              autoHideScrollbar: false,
              theme: 'dark',
              advanced:{
                     updateOnContentResize: true
              },
              scrollButtons: {
                     scrollAmount: 'auto', 
                     enable: true 
              },
        });
</script>
```

**But thats not fine, need to fix this issue or so called bug.**

**Comment by iominh** [comment]
Hi @MorpherQAlpha,

Perhaps try adding a container element around anything you want ng-scrollbars applied to. For example:

``` js
<div ng-scrollbars ng-scrollbars-config="vertScrollConfig">
     <md-sidenav md-swipe-left="sidenav_toggle()"
          class="md-sidenav-left md-whiteframe-z2"
          md-is-locked-open="$mdMedia('gt-sm')"
          md-component-id="leftNav"
          md-scroll-y
          ...
     </md-sidenav>
</div>
```

Please see http://iominh.github.io/ng-scrollbars/10.html and view source on the page

Minh

**Comment by sirb0rab0g1** [comment]
<div layout="column" ng-cloak="" class="sidenavdemoBasicUsage wow fadeIn animated">
	<section layout="row" flex="">
		<md-sidenav class="md-sidenav-left" md-component-id="left" md-is-locked-open="$mdMedia('gt-md')" md-whiteframe="4">
		</md-sidenav>  
		<md-sidenav class="md-sidenav-left" md-component-id="left" md-is-locked-open="$mdMedia('gt-md')" md-whiteframe="4" style="position:fixed;">
		<md-toolbar class="md-theme-indigo">
			<h1 class="md-toolbar-tools">Sidenav Left</h1>
		</md-toolbar>
		<md-content layout-padding="">
			<p hide="" show-gt-md="" >
				This sidenav is locked open on your device. To go back to the default behavior,
				narrow your display.
			</p>
		</md-content>
		</md-sidenav>
		
		<md-content flex>
			<md-toolbar class="md-hue-2">
			
			</md-toolbar>

			<md-content layout="column" >
				<p>
				The left sidenav will 'lock open' on a medium (>=960px wide) device.
				</p>
				<p>
				The right sidenav will focus on a specific child element.
				</p>
			</md-content>
		</md-content>
	</section>
</div>

try this code
