### ISSUE TITLE
onScroll Callback Memory Leak

### ISSUE THREAD

**Issue by GeoffMooreMedia** [iominh/ng-scrollbars#49]
Using the onScroll callback within the config, as described in Malihu's documentation, results in a memory leak. The full scope is retained. This is true even with no code in the onScroll callback. 

To be fair, there is no reference to these callbacks within the ng-scrollbars documentation.

**Comment by GeoffMooreMedia** [comment]
Missed that one of the updateScrollbar options was to destroy it. Destroying the scrollbar when the scope is destroyed releases all memory. 
`$scope.$on('$destroy',function(){
    $scope.updateScrollbar('destroy');
});`

**Comment by iominh** [comment]
Thanks @GeoffMooreMedia for the ticket and also for the helpful comment! I'm sure that'll help other folks that come across that issue.

Also nice to see another DC local :), it's a small world

**Comment by GeoffMooreMedia** [comment]
Further proof that trying to trace memory leaks turns your brain to mush. Apparently destroyed my ability to fully read the documentation.
