### ISSUE TITLE
Issue with minifying

### ISSUE THREAD

**Issue by iMomen** [iominh/ng-scrollbars#73]
I'm using Grunt Uglify to minify and concatenate my bower files
when I do so I got this error 
`dx is not defined
at HTMLDivElement._resetContentPosition (jquery.mCustomScrollbar.js:1044)`

which is this line
`var cx=dx=0;`

any hint to overcome this?

**Comment by Suraj786** [comment]
Hi @iMomen ,

Please check this link:
https://github.com/malihu/malihu-custom-scrollbar-plugin/issues/459#issuecomment-247314561

Try updating from `var cx = dx = 0;` to `var cx, dx = 0;`
